### ISSUE TITLE
Detail Pages Details Links Broken

### ISSUE THREAD

**Issue by scotthewitt** [inukshuk/jekyll-scholar#55]
Links from a bibliography page to the details of an entry via the details page functionality does not work as documented due to the default permalink setting of pretty with Jekyll 2.2.0.

bibliography/ruby.html is actually made as bibliography/ruby/index.html under default settings

**Comment by clement-moulin-frier** [comment]
Hi,

The fix still results in a broken link when using "permalink: pretty", since it points to, e.g., bibliography/ruby/index.html, whereas the actual file is at bibliography/ruby/index/index.html

**Comment by inukshuk** [comment]
Thanks for pointing that out -- should be fixed now!

**Comment by clement-moulin-frier** [comment]
Hi,

We are close to solve the problem ;) 
A "/" (slash) is missing before "index" in 0a84968. I added it to my fork, but actually it still doesnt solve the problem. Now the link points to bibliography/ruby/index/index.html as we wanted, but the actual file path actually contains one more "/index", i.e is located at bibliography/ruby**/index/index**/index.html

**Comment by inukshuk** [comment]
OK this time it should work!

I made sure that there is no double index in the file path, too (that would kind of defeat the intention of pretty links...).

**Comment by clement-moulin-frier** [comment]
Hi,

After not having updated my website since a few months, I had to re-generate it and I still encounter the same kind of issue, where the details links are broken. See an example here: http://clement-moulin-frier.github.io/#publications

The first "Details" links for example, points to http://clement-moulin-frier.github.io/bibliography/moulinfrier2015cosmoindex/index.html

whereas the actual detail page is at http://clement-moulin-frier.github.io/bibliography/moulinfrier2015cosmoindex/index/index.html

(with "Index" appearing three times in the url).

Any hint about how to fix that?

Thanks a lot

**Comment by inukshuk** [comment]
S

**Comment by inukshuk** [comment]
Can you try to create a failing test case for this?

As you can see our current tests don't have the issue you are seeing.

With default settings: https://github.com/inukshuk/jekyll-scholar/blob/master/features/details.feature#L142

With permalink set to 'pretty': https://github.com/inukshuk/jekyll-scholar/blob/master/features/details.feature#L186

**Comment by clement-moulin-frier** [comment]
Sorry you're right, I still had an old version of jekyll-scholar. I've upgraded it and it works like a charm.
Thanks!
